### ISSUE TITLE
Implement `mv` for the private file system

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/rs-wnfs#54]
`mv` is much more complicated in the private file system because we need to modify the namefilters of everything in the tree that's moved.

I think it may also be useful to separate out `mv` into `cp` + `rm`.

**Comment by appcypher** [comment]
In https://github.com/wnfs-wg/rs-wnfs/pull/59, I introduced an `attach` op because `cp` + `rm` for `mv` would result in more file operations. `rm` + `add` is better than a `get` + `add` + `rm`.

Now `attach` takes a node and a destination and fixes the node subtree bare names and ratchets. So `cp` = `get` + `attach`, and `mv` = `rm` + `attach`
